// @ts-ignore
import "~/styles/globals.css";
import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { AuthUiProvider } from "./providers";
import { SignedIn, UserButton, SignedOut } from "@daveyplate/better-auth-ui";
import Link from "next/link";
import { Button } from "~/components/ui/button";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="dark bg-black">
        <AuthUiProvider>
          <TRPCReactProvider>
            <nav className="flex w-full flex-row items-center justify-between gap-4 p-4">
              <div className="flex flex-row items-center gap-4">
                <Link href="/public">Public quotes</Link>
              </div>
              <div className="flex flex-row items-center gap-4">
                <SignedIn>
                  <Link href="/">Your quotes</Link>
                  <Link href="/quoted">Quotes about you</Link>
                  <UserButton
                    size={"icon"}
                    className="border border-neutral-950 bg-neutral-900 text-white hover:bg-neutral-950"
                  />
                </SignedIn>
                <SignedOut>
                  <Button variant="outline">
                    <Link href="/auth/sign-in">Sign In</Link>
                  </Button>
                </SignedOut>
              </div>
            </nav>
            {children}
          </TRPCReactProvider>
        </AuthUiProvider>
      </body>
    </html>
  );
}
